import os
import psycopg2
from psycopg2 import OperationalError, errorcodes, extras
from flask import Flask, request, jsonify

# --- 1. CONFIGURATION ---
# IMPORTANT: Replace these placeholders with your actual PostgreSQL credentials.
DB_CONFIG = {
    "host": "avo-adb-002.postgres.database.azure.com",
    "database": "RFQ_DATA",
    "user": "administrationSTS",
    "password": "St$@0987"
}

app = Flask(__name__)

# --- 2. DATABASE CONNECTION UTILITY ---

def get_db():
    """Returns a PostgreSQL database connection and a RealDictCursor."""
    conn = None
    try:
        # Establish connection using the configuration dictionary
        conn = psycopg2.connect(**DB_CONFIG)
        # Set the row factory to return dictionaries
        cursor = conn.cursor(cursor_factory=extras.RealDictCursor)
        return conn, cursor
    except OperationalError as e:
        # Log the specific connection failure
        print(f"PostgreSQL connection failed: {e}")
        # Re-raise the error to be handled by the API endpoint caller
        if conn:
            conn.close()
        # Use str(e) as a fallback if e.pgerror is not available (common in connection errors)
        error_message = f"Database connection failed: {str(e)}"
        raise ConnectionError(error_message)
    except Exception as e:
        if conn:
            conn.close()
        raise e


# --- 3. API ENDPOINTS ---

@app.route('/api/rfq/submit', methods=['POST'])
def submit_rfq_data():
    """Receives structured RFQ data and inserts it into the main and contact tables."""
    data = request.get_json()
    conn = None
    rfq_id = None
    
    if not data:
        return jsonify({"status": "error", "message": "No data provided"}), 400

    rfq_id = data.get('rfq_id')
    if not rfq_id:
        return jsonify({"status": "error", "message": "Missing required field: rfq_id"}), 400

    try:
        # 1. Establish connection
        conn, cursor = get_db()
        
        # Start transaction block
        
        # --- CONTACT HANDLING (1:N Relationship) ---
        contact_data = data.get('contact', {})
        contact_email = contact_data.get('email')
        
        if not contact_email:
            conn.close()
            return jsonify({"status": "error", "message": "Missing required contact field: email"}), 400

        contact_id_fk = None

        # A. Try to find existing contact by email
        cursor.execute(
            "SELECT contact_id FROM contact WHERE contact_email = %s", 
            (contact_email,)
        )
        existing_contact = cursor.fetchone()

        if existing_contact:
            # Contact found, use existing ID
            contact_id_fk = existing_contact['contact_id']
        else:
            # B. Contact not found, insert new contact and retrieve its new ID
            insert_contact_sql = """
            INSERT INTO contact (contact_role, contact_email, contact_phone)
            VALUES (%s, %s, %s)
            RETURNING contact_id;
            """
            cursor.execute(
                insert_contact_sql,
                (
                    contact_data.get('role'),
                    contact_data.get('email'),
                    contact_data.get('phone')
                )
            )
            # Fetch the ID generated by SERIAL
            contact_id_fk = cursor.fetchone()['contact_id']

        # --- MAIN RFQ INSERTION ---

        # 2. Prepare main data fields
        # Note: Psycopg2 handles Python's True/False correctly for PostgreSQL BOOLEAN.
        main_fields = {
            'rfq_id': rfq_id,
            'customer_name': data.get('customer_name'),
            'application': data.get('application'),
            'product_line': data.get('product_line'),
            'customer_pn': data.get('customer_pn'),
            'revision_level': data.get('revision_level'),
            'delivery_zone': data.get('delivery_zone'),
            'delivery_plant': data.get('delivery_plant'),
            'sop_year': data.get('sop_year'),
            'annual_volume': data.get('annual_volume'),
            'rfq_reception_date': data.get('rfq_reception_date'),
            'quotation_expected_date': data.get('quotation_expected_date'),
            'target_price_eur': data.get('target_price_eur'),
            'delivery_conditions': data.get('delivery_conditions'),
            'payment_terms': data.get('payment_terms'),
            'business_trigger': data.get('business_trigger'),
            'entry_barriers': data.get('entry_barriers'),
            'product_feasibility_note': data.get('product_feasibility_note'),
            'manufacturing_location': data.get('manufacturing_location'),
            'risks': data.get('risks'),
            'decision': data.get('decision'),
            'design_responsibility': data.get('design_responsibility'),
            'validation_responsibility': data.get('validation_responsibility'),
            'design_ownership': data.get('design_ownership'),
            'development_costs': data.get('development_costs'),
            'technical_capacity': data.get('technical_capacity', 'maybe').lower() in ['yes', 'true'],
            'scope_alignment': data.get('scope_alignment', 'maybe').lower() in ['yes', 'true'],
            'overall_feasibility': data.get('overall_feasibility'),
            'customer_status': data.get('customer_status'),
            'strategic_note': data.get('strategic_note'),
            'final_recommendation': data.get('final_recommendation'),
            'contact_id_fk': contact_id_fk # The ID determined above
        }
        
        main_columns = ', '.join(main_fields.keys())
        main_placeholders = ', '.join(['%s'] * len(main_fields))
        main_values = list(main_fields.values())

        insert_main_sql = f"""
        INSERT INTO main ({main_columns})
        VALUES ({main_placeholders})
        """
        
        # 3. Execute main insertion
        cursor.execute(insert_main_sql, main_values)
        
        # 4. Commit the transaction if successful
        conn.commit()

        return jsonify({
            "status": "success", 
            "message": "RFQ data successfully stored.", 
            "rfq_id": rfq_id
        }), 201

    except ConnectionError as e:
        # Handled in get_db for connection issues
        return jsonify({"status": "error", "message": str(e)}), 500

    except OperationalError as e:
        if conn:
            conn.rollback()
            
        # Safely extract PostgreSQL error details
        pg_error_message = getattr(e, 'pgerror', None)
        detail_message = pg_error_message.strip() if pg_error_message else str(e)

        return jsonify({
            "status": "error",
            "message": f"Database insertion failed (PostgreSQL Error): {detail_message}",
            "rfq_id": rfq_id if rfq_id else None
        }), 500

    except Exception as e:
        if conn:
            conn.rollback()
            
        return jsonify({"status": "error", "message": f"An unexpected error occurred: {e}"}), 500
        
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()

if __name__ == '__main__':
    # When running locally, set the FLASK_APP environment variable.
    # On Azure, gunicorn will handle execution.
    app.run(debug=True)
